### ISSUE TITLE
获取星铁抽卡记录使用authKeyB会提示authkey error

### ISSUE THREAD

**Issue by qhy040404** [UIGF-org/mihoyo-api-collect#10]

**Comment by Kamisato-Ayaka-233** [comment]
emmmm，`game_biz`参数对嘛？不要获取成原神或其它游戏的Auth Key B了。还有就是不要用时间比较久的Auth Key，如果过期了需要重新获取的。

**Comment by qhy040404** [comment]
biz没错，是`hkrpg_cn`

**Comment by qhy040404** [comment]
获取authkey能正常返回，但是跃迁那个api就会报错

**Comment by qhy040404** [comment]
研究了一下，authkeyb的长度不对
url编码后的authkeyb长度大约在370左右，抓到的url中authkey长度大概为730

**Comment by qhy040404** [comment]
感觉星铁好像又是另外一个authkey

**Comment by Kamisato-Ayaka-233** [comment]
我只是用Auth Key B测试原神的祈愿，是可以的。而星穹铁道的跃迁没测试过……

**Comment by qhy040404** [comment]
> 我只是用Auth Key B测试原神的祈愿，是可以的。而星穹铁道的跃迁没测试过……

悲

**Comment by qhy040404** [comment]
authkeyB的长度固定为345，崩铁的authkey长度固定为685（不经过url编码）

**Comment by Kamisato-Ayaka-233** [comment]
好奇怪，我现在没法用之前的办法获取Auth Key B了……

**Comment by qhy040404** [comment]
我原的还是能用

**Comment by Kamisato-Ayaka-233** [comment]
emm，用K2`salt`就可以了诶。

（哎呦，文档写错了……）

**Comment by qhy040404** [comment]
> emm，用K2`salt`就可以了诶。
> 
> （哎呦，文档写错了……）

可是原的抽卡记录得用lksalt

**Comment by Kamisato-Ayaka-233** [comment]
可以了，文档改好了。

**Comment by qhy040404** [comment]
崩铁的AuthKey长度还是不对 😭

**Comment by Kamisato-Ayaka-233** [comment]
我不清楚崩铁的情况了。因为我也没办法获取崩铁的Auth Key B

**Comment by Kamisato-Ayaka-233** [comment]
好吧，实际上就不能通过这个Auth Key获取到抽卡记录。原神那个功能只是巧合而已罢了。

**Comment by qhy040404** [comment]
> 好吧，实际上就不能通过这个Auth Key获取到抽卡记录。原神那个功能只是巧合而已罢了。
乐

**Comment by Kamisato-Ayaka-233** [comment]
对不起哈，我弄错了……
