### ISSUE TITLE
Apifox 上的 UIGF 团队

### ISSUE THREAD

**Issue by Lightczx** [UIGF-org/mihoyo-api-collect#29]
Apifox 中维护了大量的 API（半成品），现在欢迎社区人士的加入

DismissedLight 在 Apifox 中邀请你加入团队 UIGF https://app.apifox.com/invite?token=VtE-VfmGnEtA4E_Khmct6

由于链接 7 天就会过期，可以在这个Issue下回复我，我会及时更新链接

**Comment by Lightczx** [comment]
https://app.apifox.com/invite?token=xiWmfXGha1OJqSWS5KPp_

**Comment by Lightczx** [comment]
https://app.apifox.com/invite?token=szFvqf_3bSIrQC1DIlz1v

**Comment by Lightczx** [comment]
> 另外这个Apifox会在C盘下面乱拉屎

你应该去找他们的开发反馈

**Comment by CPTProgrammer** [comment]
请求更新链接

**Comment by Lightczx** [comment]
https://app.apifox.com/invite?token=B8WByfn2548a-wZ1Y5pwG

**Comment by Theresa-0328** [comment]
请求更新链接

**Comment by caoguirong** [comment]
请求更新链接

**Comment by Lightczx** [comment]
https://app.apifox.com/invite?token=fO0u3hrtxM2GtK8mMZOiS
