### ISSUE TITLE
并入UIGF官网文档

### ISSUE THREAD

**Issue by Lightczx** [UIGF-org/mihoyo-api-collect#3]
虽然有些地方有点错误，但是总体整理的还是不错的，有没有兴趣并入到UIGF的文档里面呢

**Comment by Kamisato-Ayaka-233** [comment]
可以的，谢了。

**Comment by Lightczx** [comment]
> 关于ds算法的随机串似乎已经从纯数字变为了六位（数字/大小写字母）字符串了

本身就有2套DS算法，在不同的平台上实现方式也步进相同，甚至某些原本只传入数字的接口，同样可以使用字符

**Comment by Lightczx** [comment]
> 可以的，谢了。
> 
> 还有，可以请指出一下文档有哪些错误吗？

那就直接先整个库挪到UIGF组织下面吧

**Comment by tllvmys** [comment]
> > 关于ds算法的随机串似乎已经从纯数字变为了六位（数字/大小写字母）字符串了
> 
> 本身就有2套DS算法，在不同的平台上实现方式也不尽相同，甚至某些原本只传入数字的接口，同样可以使用字符

可以问问大佬web端的salt储存在哪里吗？找了好几天了

**Comment by Kamisato-Ayaka-233** [comment]
> 关于ds算法的随机串似乎已经从纯数字变为了六位（数字/大小写字母）字符串了

没有呀，你说的是国际版米游社吧？

国际版API应该才是这样的，不过我没研究过国际版API，只是在其它仓库中康到过一些国际版API的`DS`生成方式。

**Comment by Kamisato-Ayaka-233** [comment]
> > 可以的，谢了。
> > 还有，可以请指出一下文档有哪些错误吗？
> 
> 那就直接先整个库挪到UIGF组织下面吧

好啦

**Comment by Masterain98** [comment]
https://github.com/UIGF-org/UIGF-org.github.io/pull/14

**Comment by tllvmys** [comment]
> > 关于ds算法的随机串似乎已经从纯数字变为了六位（数字/大小写字母）字符串了
> 
> 没有呀，你说的是国际版米游社吧？
> 
> 国际版API应该才是这样的，不过我没研究过国际版API，只是在其它仓库中康到过一些国际版API的`DS`生成方式。

是中国米游社网页端，APP里是数字，网页里是这样的1684254446,ZQFRnE,53cc39779ec799e6898b7c6941adcf26

**Comment by tllvmys** [comment]
谢谢大佬，已经弄好了🌹
