### ISSUE TITLE
签到api可能变了

### ISSUE THREAD

**Issue by gszshdzz** [UIGF-org/mihoyo-api-collect#32]
几个签到软件都无法签到了（活动已结束）

**Comment by MoRanYue** [comment]
请问具体是指哪个“签到”呢？
是游戏道具签到，还是社区打卡呢？

**Comment by gszshdzz** [comment]
> 请问具体是指哪个“签到”呢？ 是游戏道具签到，还是社区打卡呢？
> 
> （有一段时间没有使用签到工具了）

米游社原神每日签到， 发邮件的那个
![image](https://github.com/UIGF-org/mihoyo-api-collect/assets/68946978/6d8f4334-57b6-49bf-8e72-9433f51ea026)
（电脑：snap hutao）
![Screenshot_2023-12-03-08-21-48-054_com mukapp genshintool](https://github.com/UIGF-org/mihoyo-api-collect/assets/68946978/0de1a1d0-f11d-44d4-8d52-0e063364a981)

**Comment by MoRanYue** [comment]
刚刚去稍微抓包了下，找出了这里认为和签到相关的API
（接口似乎确实变了呢）

POST https://api-takumi.mihoyo.com/event/luna/sign

Req Body
```
{
  "act_id": "e202311201442471",
  "region": "cn_gf01",
  "uid": "222681079",
  "lang": "zh-cn"
}
```
Res Body
```
{
  "retcode": 0,
  "message": "OK",
  "data": {
    "code": "",
    "risk_code": 0,
    "gt": "",
    "challenge": "",
    "success": 0,
    "is_risk": false
  }
}
```
GET https://api-takumi.mihoyo.com/event/luna/info?lang=zh-cn&act_id=e202311201442471%C2%AEion=cn_gf01&uid=222681079
Res Body
```
{
  "retcode": 0,
  "message": "OK",
  "data": {
    "total_sign_day": 0,
    "today": "2023-12-03",
    "is_sign": false,
    "is_sub": false,
    "region": "",
    "sign_cnt_missed": 2,
    "short_sign_day": 0
  }
}
```

GET https://api-takumi.mihoyo.com/event/luna/extra_award?act_id=e202311201442471&uid=222681079%C2%AEion=cn_gf01&lang=zh-cn

GET https://api-takumi.mihoyo.com/event/luna/extra_award?act_id=e202311201442471&lang=zh-cn

Res Body
```{
  "retcode": 0,
  "message": "OK",
  "data": {
    "awards": [
      {
        "id": 0,
        "icon": "https://webstatic.mihoyo.com/upload/event/2020/09/29/97a77a51901207ba1c4b167d7484742b_879413631620747219.png%22,
        "name": "原石",
        "cnt": 100,
        "sign_day": 1
      },
      {
        "id": 0,
        "icon": "https://webstatic.mihoyo.com/upload/event/2020/09/29/65bb84b6cfe567a52495cbd814dc0729_3166173192087337217.png%22,
        "name": "摩拉",
        "cnt": 10000,
        "sign_day": 1
      }
    ],
    "total_cnt": 0,
    "ys_first_award": true,
    "has_short_act": false,
    "short_act_info": {
      "awards": [],
      "start_timestamp": "0",
      "end_timestamp": "0",
      "total_cnt": 0
    }
  }
}
```
GET https://api-takumi.mihoyo.com/event/luna/home?lang=zh-cn&act_id=e202311201442471

Res Body
```
签到获得物品的信息
```

几乎每个请求的请求头中都含有User-Agent、DS、x-rpc-signgsme=hk4e、Origin和Referer=https://act.mihoyo.com/
Cookie含有通过
https://passport-api.mihoyo.com/account/auth/api/getCookieAccountInfoBySToken
获取的Cookie Token、LToken（此处的抓包结果为V1）、DEVICEFP（通过platform为5获取的）

**Comment by stuchilde** [comment]
这个需要抓取https://bbs-api.miyoushe.com/apihub/api/home/new?gids=2接口的签到act_id才行
