### ISSUE TITLE
获取游戏信息返回5003错误

### ISSUE THREAD

**Issue by caoguirong** [UIGF-org/mihoyo-api-collect#37]
请求获取游戏信息的接口给我返回了如下错误，不知道是我哪一步错了，求大佬指点
{"data":null,"message":"","retcode":5003}

**Comment by caoguirong** [comment]
> 缺少合法设备信息引起的，建议参考 deviceFp 获取相关内容

谢谢

**Comment by BTMuli** [comment]
> 谢谢

如果问题已经解决，请关闭本issue，感谢
