### ISSUE TITLE
DS的英文名称

### ISSUE THREAD

**Issue by Lightczx** [UIGF-org/mihoyo-api-collect#4]
从作用上讲 DS 应该是 DataSign（数据签名）而不是 Dynamic Secret（动态密钥）

**Comment by Kamisato-Ayaka-233** [comment]
我认为，从严格定义上来说，“数据签名”的目的是校验数据是否正常或从正确途径获取，以及在数据传输或生成过程中由第三者修改，是为了保证数据安全与完整。

而“密钥”则是一种

**Comment by Lightczx** [comment]
> “数据签名”的目的是校验数据是否正常或从正确途径获取

不正是么😂

**Comment by Kamisato-Ayaka-233** [comment]
> > “数据签名”的目的是校验数据是否正常或从正确途径获取
> 
> 不正是么😂

emmm，“数据签名”应该是用来**校验**数据的，不应该是用来反爬虫的呀。
