### ISSUE TITLE
关于`login_ticket`，请问一下哪个API是可以30分钟刷新它？

### ISSUE THREAD

**Issue by CainLuo** [UIGF-org/mihoyo-api-collect#41]
关于`login_ticket`，请问一下哪个API是可以30分钟刷新它？

**Comment by MoRanYue** [comment]
可以康康[这篇文档](https://github.com/UIGF-org/mihoyo-api-collect/blob/main/hoyolab%2Flogin%2Fpassword_passport.md)呀

**Comment by BTMuli** [comment]
<details>
  <summary>一些废话</summary>
   
`login_ticket` 刷新是没有必要的，都是通过 `login_ticket` 来获取 `cookie_token` 等其他可以直接使用的 token，在获取完后 `login_ticket` 就没用了

而且 `login_ticket` 有效期短（相比其他按天算的，这个只有半小时），获取复杂度高（跑脚本生成与用户登录从 document 获取，前者复杂很多），个人建议使用其他方式保持登录状态。
</details>

**Comment by CainLuo** [comment]
> 一些废话
> `login_ticket` 刷新是没有必要的，都是通过 `login_ticket` 来获取 `cookie_token` 等其他可以直接使用的 token，在获取完后 `login_ticket` 就没用了
> 
> 而且 `login_ticket` 有效期短（相比其他按天算的，这个只有半小时），获取复杂度高（跑脚本生成与用户登录从 document 获取，前者复杂很多），个人建议使用其他方式保持登录状态。

@BTMuli 那如何做到不用login_ticket去请求到类似星铁的已拥有角色？还有养成材料计算等接口？

**Comment by BTMuli** [comment]
> @BTMuli 那如何做到不用login_ticket去请求到类似星铁的已拥有角色？还有养成材料计算等接口？


login_ticket只是敲门砖，相当于（等同于）你米社的用户登录，只有登录才能获取用户数据。

但是就像登录不是只能用密码，还能用手机验证等一样，登录态的校验并不（据我所知只有通行证页面如此）只靠login_ticket，更多的是诸如 cookie_token stoken mid这种

上面提到的各种token才是获取数据的钥匙，login_ticket只是前置

接口数据获取这个可以看文档或者第三方工具的实现，SRGF那边有一排参考应用，或者自己爬请求

（真爬到就会发现哪怕reqHeader里面有login_ticket，实际上并没有参与校验，有效与否并不影响）

~~（这边打个广告，如果嫌安卓怕请求麻烦，可以用我的TeyvatGuide，通过JSBridge模拟获取游戏数据，pc请求爬取还是比安卓方便的x）~~

**Comment by CainLuo** [comment]
> > @BTMuli 那如何做到不用login_ticket去请求到类似星铁的已拥有角色？还有养成材料计算等接口？
> 
> login_ticket只是敲门砖，相当于（等同于）你米社的用户登录，只有登录才能获取用户数据。
> 
> 但是就像登录不是只能用密码，还能用手机验证等一样，登录态的校验并不（据我所知只有通行证页面如此）只靠login_ticket，更多的是诸如 cookie_token stoken mid这种
> 
> 上面提到的各种token才是获取数据的钥匙，login_ticket只是前置
> 
> 接口数据获取这个可以看文档或者第三方工具的实现，SRGF那边有一排参考应用，或者自己爬请求
> 
> （真爬到就会发现哪怕reqHeader里面有login_ticket，实际上并没有参与校验，有效与否并不影响）
> 
> ~（这边打个广告，如果嫌安卓怕请求麻烦，可以用我的TeyvatGuide，通过JSBridge模拟获取游戏数据，pc请求爬取还是比安卓方便的x）~

@BTMuli 我现在在的是Mac端的App，在其他header都正确的情况下，Cookie没有包含login_ticket，30分钟之后就没法再请求需要login_ticket的数据了，比如原神里的我的角色，星铁里的我的角色

**Comment by CainLuo** [comment]
> > @BTMuli 我现在在的是Mac端的App，在其他header都正确的情况下，Cookie没有包含login_ticket，30分钟之后就没法再请求需要login_ticket的数据了，比如原神里的我的角色，星铁里的我的角色
> 
> 巧了，TeyvatGuide可以在Mac上使用，你可以看看我是怎么请求的，获取原神角色数据还真不用login_ticket

@BTMuli 好的，非常感谢，我先试试，我不止于原神，还打算把星铁，或者后续的绝区零也加进去~

**Comment by CainLuo** [comment]
@BTMuli 获取角色的接口解决了，但是获取天赋的那个搞蒙了，我用了TeyvatGuide请求，基本上都差不多，为啥一个可以成功，一个会报请先登录？

URL:
```
https://api-takumi.mihoyo.com/event/e20200928calculate/v1/sync/avatar/detail?avatar_id=10000002&server=cn_gf01&uid=109050292
```

Reuqest Contents:
```
GET /event/e20200928calculate/v1/sync/avatar/detail?avatar_id=10000002&server=cn_gf01&uid=109050292 HTTP/1.1
Host: api-takumi.mihoyo.com
Accept: */*
Connection: keep-alive
Cookie: account_id=182692936; cookie_token=JehTWNlBuzMaJquN7YZtTumPzheRcDuGVMCTlZH5
User-Agent: MiTool/1.0.0 (caom.cainluo.MiTool; build:1; macOS 13.6.4) Alamofire/5.9.0
Accept-Language: zh-Hans-CN;q=1.0
Referer: https://webstatic.mihoyo.com/
Accept-Encoding: br;q=1.0, gzip;q=0.9, deflate;q=0.8
```

Response:
```
{"data":null,"message":"请先登录","retcode":-100}
```

**Comment by BTMuli** [comment]
> @BTMuli 基本上都差不多，为啥一个可以成功，一个会报请先登录？

cookie_token 这种隐私数据不要明文放进来，帮你删掉了

字段错了，不是 server 是 region

**Comment by CainLuo** [comment]
> > @BTMuli 基本上都差不多，为啥一个可以成功，一个会报请先登录？
> 
> cookie_token 这种隐私数据不要明文放进来，帮你删掉了
> 
> 字段错了，不是 server 是 region

@BTMuli  哦哦哦，感谢大佬，成功了，老眼昏花了，看不清字段😂

**Comment by BTMuli** [comment]
关于 login_ticket 的讨论可以视为解决，故关闭本issue，有什么其他问题建议另开一个
