### ISSUE TITLE
关于"原神游戏信息"获取的api

### ISSUE THREAD

**Issue by SC0624a** [UIGF-org/mihoyo-api-collect#42]
如题，貌似被老米给和谐了，在原来没被和谐的时候经常会遇到图片验证

**Comment by BTMuli** [comment]
能否详细说明，比如具体到哪个请求 API 或者提供复现条件

**Comment by SC0624a** [comment]
https://github.com/UIGF-org/mihoyo-api-collect/blob/main/hoyolab/user/game_account_info.md#%E5%8E%9F%E7%A5%9E

这个标题下面的全都被和谐了

**Comment by BTMuli** [comment]
> 这个标题下面的全都被和谐了

😅😅😅
