### ISSUE TITLE
login_ticket获取stoken和ltoken的接口好像改了

### ISSUE THREAD

**Issue by Yoimiya-993** [UIGF-org/mihoyo-api-collect#46]
![image](https://github.com/UIGF-org/mihoyo-api-collect/assets/52495231/3563d087-be54-4126-8eb2-aac0354c8eb4)
![image](https://github.com/UIGF-org/mihoyo-api-collect/assets/52495231/8c06f206-a1c3-4808-9ae5-de6fd1c23fe7)
![image](https://github.com/UIGF-org/mihoyo-api-collect/assets/52495231/948306cf-4b05-4005-8f54-653ec7f71fa6)

**Comment by Yoimiya-993** [comment]
只能拿到 ltkoen 了

**Comment by BTMuli** [comment]
已知问题，下午的时候已经有UIGF成员发现了，目前已经确定无法通过`login_ticket`获取`stoken`

**Comment by 1714775263** [comment]
无法解决了吗还是需要新的接口

**Comment by BTMuli** [comment]
> 那从stoken还可以获取到authkey吗？

变动只是影响 `stoken` 的获取渠道，`stoken` 之后的相关请求，如 `stokenv1 → stokenv2`，`stokenv2 → gachalog` 等不受影响

**Comment by TRIM5829** [comment]
> > 那从stoken还可以获取到authkey吗？
> 
> 变动只是影响 `stoken` 的获取渠道，`stoken` 之后的相关请求，如 `stokenv1 → stokenv2`，`stokenv2 → gachalog` 等不受影响

现在只有扫码才能换到stoken，也许这次更新后authkey改为在本地计算了

**Comment by SSB-ARFCN** [comment]
國際服也改了
