### ISSUE TITLE
实时便签api

### ISSUE THREAD

**Issue by MTpupil** [UIGF-org/mihoyo-api-collect#5]
https://api-takumi-record.mihoyo.com/game_record/app/genshin/api/dailyNote 获取游戏内实时数据的api，我通过快捷指令做了一个快速查看，然后使用圈x做了一个监控脚本，但是经常发生数据无法获取的情况，retcode是1034。

在米游社打开便签页面会提示账号异常，通过验证码之后恢复，但是过段时间还会这样。

**Comment by BennettChina** [comment]
`1034` 是获取数据触发反爬虫遇到验证码的返回 `code`，目前这个还是挺难处理的。

**Comment by MTpupil** [comment]
> `1034` 是获取数据触发反爬虫遇到验证码的返回 `code`，目前这个还是挺难处理的。

如果说无法避免的话，有什么方法可以在触发之后进行验证么。tg上面有一个派蒙机器人，可以直接调起验证页面，不知道是用了什么接口还是其他的。

**Comment by BennettChina** [comment]
> > `1034` 是获取数据触发反爬虫遇到验证码的返回 `code`，目前这个还是挺难处理的。
> 
> 如果说无法避免的话，有什么方法可以在触发之后进行验证么。tg上面有一个派蒙机器人，可以直接调起验证页面，不知道是用了什么接口还是其他的。

 具体你可以参考这两个项目的处理函数。
- `nodejs` 项目：[验证码处理方案](https://github.com/SilveryStar/Adachi-BOT/blob/ca7ee89caafa9e0b8810addd2129ef77993732c7/src/plugins/genshin/utils/api.ts#L628)

- `python` 项目：[验证码处理方案2](https://github.com/Womsxd/MihoyoBBSTools/blob/9f8bcd4d257c36a225dc14c47fc16ee1cb064fd1/mihoyobbs.py#L55)

**Comment by MTpupil** [comment]
> > > `1034` 是获取数据触发反爬虫遇到验证码的返回 `code`，目前这个还是挺难处理的。
> 
> > 
> 
> > 如果说无法避免的话，有什么方法可以在触发之后进行验证么。tg上面有一个派蒙机器人，可以直接调起验证页面，不知道是用了什么接口还是其他的。
> 
> 
> 
>  具体你可以参考这两个项目的处理函数。
> 
> - `nodejs` 项目：[验证码处理方案](https://github.com/SilveryStar/Adachi-BOT/blob/ca7ee89caafa9e0b8810addd2129ef77993732c7/src/plugins/genshin/utils/api.ts#L628)
> 
> 
> 
> - `python` 项目：[验证码处理方案2](https://github.com/Womsxd/MihoyoBBSTools/blob/9f8bcd4d257c36a225dc14c47fc16ee1cb064fd1/mihoyobbs.py#L55)
好的谢谢

**Comment by Kamisato-Ayaka-233** [comment]
米游社和b站一样，也用的是极验（GeeTest）的验证码服务吧。

**Comment by Kamisato-Ayaka-233** [comment]
米游社和b站一样，也用的是极验（GeeTest）的验证码服务吧。

**Comment by MTpupil** [comment]
> 米游社和b站一样，也用的是极验（GeeTest）的验证码服务吧。

我记得是这个没错。

**Comment by Witnesscm** [comment]
https://github.com/Witnesscm/Yunzai-plugin/blob/main/%E4%BD%93%E5%8A%9B%E5%85%8D%E9%AA%8C%E8%AF%81%E7%A0%81.js
暂时没验证码的方案，后续会不会加码未知

**Comment by Kamisato-Ayaka-233** [comment]
> https://github.com/Witnesscm/Yunzai-plugin/blob/main/%E4%BD%93%E5%8A%9B%E5%85%8D%E9%AA%8C%E8%AF%81%E7%A0%81.js
> 暂时没验证码的方案，后续会不会加码未知

是个办法，不过其实只要传入个合法的`x-rpc-device_fp`就行了呀。好像FP是不会变的。

**Comment by MTpupil** [comment]
> > https://github.com/Witnesscm/Yunzai-plugin/blob/main/%E4%BD%93%E5%8A%9B%E5%85%8D%E9%AA%8C%E8%AF%81%E7%A0%81.js
> > 暂时没验证码的方案，后续会不会加码未知
> 
> 是个办法，不过其实只要传入个合法的`x-rpc-device_fp`就行了呀。好像FP是不会变的。

对的，之前我每请求一次就会导致出现验证，排查之后是这个参数的原因，加了这个参数之后，不会那么频繁了，但依然保持在一天会弹一次或两次验证的频率（我的监控脚本每小时会自动请求一次）

**Comment by Witnesscm** [comment]
> > https://github.com/Witnesscm/Yunzai-plugin/blob/main/%E4%BD%93%E5%8A%9B%E5%85%8D%E9%AA%8C%E8%AF%81%E7%A0%81.js
> > 暂时没验证码的方案，后续会不会加码未知
> 
> 是个办法，不过其实只要传入个合法的`x-rpc-device_fp`就行了呀。好像FP是不会变的。

实测不太行，仅仅是降低了出现验证码的频率，还是有概率出验证码，一但出现验证码必须手动过掉，这个方法目前是100%没有验证码的

**Comment by MTpupil** [comment]
> > > https://github.com/Witnesscm/Yunzai-plugin/blob/main/%E4%BD%93%E5%8A%9B%E5%85%8D%E9%AA%8C%E8%AF%81%E7%A0%81.js
> 
> > > 暂时没验证码的方案，后续会不会加码未知
> 
> > 
> 
> > 是个办法，不过其实只要传入个合法的`x-rpc-device_fp`就行了呀。好像FP是不会变的。
> 
> 
> 
> 实测不太行，仅仅是降低了出现验证码的频率，还是有概率出验证码，一但出现验证码必须手动过掉，这个方法目前是100%没有验证码的

对的，只能降低频率，不能完全无视验证码。我之前考虑过小组件的api，不过我需要的东西比较多，所以抛弃这个方案了。

**Comment by Kamisato-Ayaka-233** [comment]
> > > https://github.com/Witnesscm/Yunzai-plugin/blob/main/%E4%BD%93%E5%8A%9B%E5%85%8D%E9%AA%8C%E8%AF%81%E7%A0%81.js
> > > 暂时没验证码的方案，后续会不会加码未知
> > 
> > 是个办法，不过其实只要传入个合法的`x-rpc-device_fp`就行了呀。好像FP是不会变的。
> 
> 实测不太行，仅仅是降低了出现验证码的频率，还是有概率出验证码，一但出现验证码必须手动过掉。
> 这个方法目前是100%没有验证码的。

请求过多的话确实会出现验证码……

**Comment by BarrZeb** [comment]
可以自己搭建手动验证码平台，也就是自己调起验证界面，或者自己搭建基于深度学习的过码

**Comment by Kamisato-Ayaka-233** [comment]
> 可以自己搭建手动验证码平台，也就是自己调起验证界面，或者自己搭建基于深度学习的过码

只需要弄个HTML页面，然后在遇到验证码时开启HTTP服务器，让人去访问这个页面来过验证码（当然如果做的项目有GUI或者是网页的话可以直接弹出窗口让人弄验证码）。

不过如果是运行在服务器的程序，或者需要定时执行的任务之类的，它们遇到验证码也没办法。想要解决，只能用一些过验证码的平台，或者AI自动过验证码了。

**Comment by Ljzd-PRO** [comment]
参考极验的文档即可：https://docs.geetest.com/sensebot/deploy/client/web
