### ISSUE TITLE
DS计算出来就是没办法对上

### ISSUE THREAD

**Issue by NOWorEVER** [UIGF-org/mihoyo-api-collect#59]
我用手机抓包数据如下
DS: 1719766520,136995,ae76c4611c3d4985d74b647e2878b625
x-rpc-client_type: 2
x-rpc-app_version: 2.71.1

按照salt表，对应的应该是
K2= rtvTthKxEyreVXQCnhluFgLXPOFKPHlA
LK2 = EJncUPGnOHajenjLhBOsdpwEMZmiCmQX
不管是用K2还是LK2，将t[1719766520]和r[136995]固定住后走算法，一直没办法得到ds的值[ae76c4611c3d4985d74b647e2878b625]
有哪位大佬帮忙解惑一下吗？还是说我的算法有问题
还是说role=和role_id=分别对应的是什么

**Comment by NOWorEVER** [comment]
我用的是POST /apihub/app/api/signIn
是这个地址有别的算法吗

**Comment by MoRanYue** [comment]
（emm，应该可以，尝试PROD salt呀）

**Comment by NOWorEVER** [comment]
import json
from hashlib import md5

# 将字典转换为JSON字符串
string1 = json.dumps({"gids": "2"})
print(string1)


def get_ds2(query: str = "", body: str = "") -> str:
    """
    获取米游社的签名字符串，用于访问米游社API时的签名验证。

    :param query: 请求的查询参数
    :param body: 请求的主体内容
    :return: 返回一个字符串，格式为"时间戳,随机字符串,签名"。
    """
    n = "t0qEgfub6cvueAPgR5m9aQWWVciEer7v"
    i = str(1719766520)
    r = str(136995)

    # 创建待签名的字符串
    sign_str = f'salt={n}&t={i}&r={r}&b={body}&q={query}'
    print(f"String to be hashed: {sign_str}")

    # 生成MD5哈希值
    c = md5(sign_str.encode('utf-8')).hexdigest()
    print(f"MD5 Hash: {c}")

    return f"{i},{r},{c}"


# 调用函数
result = get_ds2("", string1)
print(result)

我用这个算法算的，用K2,LK2,4X , 6X , PROD
算了，都是没办法算出最后这个c值。是不是算法错误了

**Comment by Fantasy156** [comment]
/apihub/app/api/signIn 我现在也是失败，另外通过抓包，用抓包的 header测试其他的打卡，也是不行，ds  对于 打卡 只能用一次了？

**Comment by NOWorEVER** [comment]
>  /apihub/app/api/signIn 我现在也是失败，另外通过抓包，用抓包的 header测试其他的打卡，也是不行，ds  对于 打卡 只能用一次了？

就算只能用一次，我这边只是测能不能通过salt算出ds值。能的话就按照这个算法直接算就好了，可惜就是不行

**Comment by Lightczx** [comment]
> 将t[1719766520]和r[136995]固定

逆天

**Comment by NOWorEVER** [comment]
> > 将t[1719766520]和r[136995]固定
> 
> 逆天

不是哥们，我手机抓包出来的三个值，然后固定两个值求第三个值有问题吗？salt确定了谁还固定这俩啊

**Comment by Lightczx** [comment]
永远不能固定

**Comment by NOWorEVER** [comment]
> 永远不能固定

哥 你没理解我的意思。
正常计算流程肯定是不能固定的。
但是我现在是为了验证salt是否正确。本地计算验证。并没有调用post这些功能啊😵

所以我才怀疑是不是我算法出问题了

**Comment by Lightczx** [comment]
另外这个接口salt是X6

**Comment by NOWorEVER** [comment]
> 另外这个接口salt是X6
> K2/LK2当然算不出来了

我也用了X6的salt去计算了，但是还是没办法匹配上😢

**Comment by MoRanYue** [comment]
> > 另外这个接口salt是X6
> > K2/LK2当然算不出来了
> 
> 我也用了X6的salt去计算了，但是还是没办法匹配上😢

由于，最后使用md5，以计算最终的DS。如此的话，需要确保以下条件相同呀：

- 请求时的数据
- 时间戳
- 随机数

**Comment by Fantasy156** [comment]
> > > 另外这个接口salt是X6 
> > > K2/LK2当然算不出来了
> > 
> > 
> > 我也用了X6的salt去计算了，但是还是没办法匹配上😢
> 
> 由于，最后使用md5，以计算最终的DS。如此的话，需要确保以下条件相同呀：
> 
> * 返回时数据
> * 问题
> * 随机数

所以现在是改了 salt 还是加上了其他的熵？

**Comment by NOWorEVER** [comment]
> 所以现在是改了 salt 还是加上了其他的熵？
这个DS是我手机抓包出来了。已经知道DS的三个值了
DS: 1719766520,136995,ae76c4611c3d4985d74b647e2878b625
然后我现在就为了测试salt，所以固定了DS前面的两个值【1719766520,136995】
现在就是用[https://github.com/UIGF-org/mihoyo-api-collect/issues/1](url)提供的salt都代入算了一下，就是没办法算出匹配的值
app的版本是:2.71.1
x-rpc-client_type: 2

我用的算法是
n = "t0qEgfub6cvueAPgR5m9aQWWVciEer7v"
i = str(1719766520)
r = str(136995)
# 创建待签名的字符串
sign_str = f'salt={n}&t={i}&r={r}&b={body}&q={query}'
print(f"String to be hashed: {sign_str}")

# 生成MD5哈希值
c = md5(sign_str.encode('utf-8')).hexdigest()
print(f"MD5 Hash: {c}")

是不是因为我的算法有问题导致的

**Comment by NOWorEVER** [comment]
> > > > 另外这个接口salt是X6
> > > > K2/LK2当然算不出来了
> > > 
> > > 
> > > 我也用了X6的salt去计算了，但是还是没办法匹配上😢
> > 
> > 
> > 由于，最后使用md5，以计算最终的DS。如此的话，需要确保以下条件相同呀：
> > 
> > * 返回时数据
> > * 问题
> > * 随机数
> 
> 所以现在是改了 salt 还是加上了其他的熵？

然后抓的包是POST /apihub/app/api/signIn

**Comment by qhy040404** [comment]
麻烦把你的完整包发出来

**Comment by BTMuli** [comment]
建议参照 [测试文件](https://github.com/BTMuli/TGAssistant/blob/master/test/getDS.test.ts) 进行测试，传入数据没给我们也没办法帮你测对不对

**Comment by NOWorEVER** [comment]
> 麻烦把你的完整包发出来

麻烦了

POST /apihub/app/api/signIn HTTP/1.1
DS: 1719764521,147016,c66ed528eebe83629f43388208d688e3
cookie: stuid=340052261;stoken=v2_I2lQdr5JCKOoFyf_kp18s2LQ7_C8laxpQlW8crWaqK5b19Pvl3E_G99mova3FuESfJUIBXcjjmn5CtM9YLtTqmbMAO_soI1HcYLeJHwTx_SBj_ALxXl5USbC.CAE=;mid=0oc9c620lb_mhy;
x-rpc-client_type: 2
x-rpc-app_version: 2.72.2
x-rpc-sys_version: 13
x-rpc-channel: xiaomi
x-rpc-device_id: 2f6d9eb5-9c4c-371c-a878-8490a3f0ce82
x-rpc-device_fp: 38d7f0d778808
x-rpc-device_name: Xiaomi M2012K10C
x-rpc-device_model: M2012K10C
x-rpc-h265_supported: 1
Referer: https://app.mihoyo.com
x-rpc-verify_key: bll8iq97cem8
x-rpc-csm_source: discussion
Content-Type: application/json; charset=UTF-8
Content-Length: 12
Host: bbs-api.miyoushe.com
Connection: Keep-Alive
Accept-Encoding: gzip
User-Agent: okhttp/4.9.3

{"gids":"2"}

**Comment by qhy040404** [comment]
![6c7c26c975805c4a316ae6e4881cadf0](https://github.com/UIGF-org/mihoyo-api-collect/assets/45379733/c764dd1b-52fc-4822-9cbd-5e27333c616b)
这不是对的吗

**Comment by NOWorEVER** [comment]
> 麻烦把你的完整包发出来



> ![6c7c26c975805c4a316ae6e4881cadf0](https://private-user-images.githubusercontent.com/45379733/344866854-c764dd1b-52fc-4822-9cbd-5e27333c616b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4OTE0NzMsIm5iZiI6MTcxOTg5MTE3MywicGF0aCI6Ii80NTM3OTczMy8zNDQ4NjY4NTQtYzc2NGRkMWItNTJmYy00ODIyLTljYmQtNWUyNzMzM2M2MTZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDAzMzI1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViYjJlNGU1N2VhYzVmMzc2YmNkZWI5NmM5ZjliOWYyNWE5NGQ1M2I2NmRlNGYyZmFmYjc2YmFlNGU3NjFkZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cOgxRo_xAm0aW7aLlsyy0iTb_Y2_g2ybBDHipGq-eEg) 这不是对的吗

f"salt={salt}&t={t}&r={r}&b={body}&q={query}"
猿来是我body代入错误了，我body用的是role。感谢，辛苦你们了

**Comment by Lightczx** [comment]
出院！

**Comment by NOWorEVER** [comment]
大佬再帮帮忙
绝区零游戏福利签到要怎么计算
body的rold是社区ID还是游戏Uid
在请求头中的x-rpc-client_type为5时使用。
通过抓包得到DS: 1724074244,1hjfbj,33d45c6229973734fc79c9332bcabdee
DS1中固定t和r，计算得到的ds匹配不上，所以只能走DS2
但是DS2中我有几个不确定的地方，就是role和role_id是同一个东西吗？
其次我找到绝区零的server=prod_gf_cn

但是我不管怎么改，都没办法获得匹配的上的DS2
这个是我的代码。麻烦大佬看看我哪里出问题了

`#DS: 1724074244,1hjfbj,33d45c6229973734fc79c9332bcabdee
import time
import random
from hashlib import md5
# JSON模块用于处理POST请求的JSON数据
import json

# 将要使用的salt，此为4X salt
salt = "xV8v4Qu54lUKrEYFZkJhB8cuOh9Asafs"
# body和query一般来说不会同时存在
# 可以使用json库的dumps函数将对象转为JSON字符串
body = json.dumps({"role": "10033377"}, sort_keys=True)
# body = '{"role":"10033377"}'
# body = '{}'
# 可以使用urllib中的parse库的urlparse函数，传入URL，得到返回值中的query字段。
# 将其转为列表（通过str.split("&")），通过sorted函数来排序，再用"&".join来将其转为最终值
# query = "&".join(sorted("server=prod_gf_cn&role_id=10033377".split("&")))
query = ""

# t = int(time.time())
# r = random.randint(100000, 200000)
# if r == 100000:
#   r = 642367

t=1724074244
r="1hjfbj"
# 也可以直接用更简单粗暴的方法
# r = random.randint(100001, 200000)
main = f"salt={salt}&t={t}&r={r}&b={body}&q={query}"
ds = md5(main.encode(encoding='UTF-8')).hexdigest()

final = f"{t},{r},{ds}" # 最终结果
print(final)`

**Comment by NOWorEVER** [comment]
> ![6c7c26c975805c4a316ae6e4881cadf0](https://github.com/UIGF-org/mihoyo-api-collect/assets/45379733/c764dd1b-52fc-4822-9cbd-5e27333c616b)
> 这不是对的吗

大佬能帮我看看最新的这个吗？是绝区零签到的
