### ISSUE TITLE
部分API会验证请求头字段`x-rpc-device_fp`

### ISSUE THREAD

**Issue by CanglongCl** [UIGF-org/mihoyo-api-collect#6]
做星铁体力查询的时候，注意到`/game_record/app/hkrpg/api/note`这个API如果长期不添加`x-rpc-device_fp`字段会**必定**触发验证码（retcode 1034），因此建议[鉴权](https://github.com/UIGF-org/mihoyo-api-collect/blob/main/other/authentication.md)中将`x-rpc-device_fp`放在“少数API才需要验证的额外的请求头”中。

**Comment by CanglongCl** [comment]
另外原神那边的`dailyNote`便笺API最近验证码触发的更频繁了，估计也和这个字段有关系，之前一直没加来着

**Comment by CanglongCl** [comment]
> 确实，没有写它的文档也是因为这个1034。
> 
> 不过，`x-rpc-device_fp`的值好像也不能随便填写吧？
> 似乎要POST请求下面这个url（不用`ds`）来获取：
> `https://public-data-api.mihoyo.com/device-fp/api/getFp`
> 
> 抓到的请求内容：
> 
> ```json
> {"device_id":"6bdc7e35-60db-434c-9ccf-90e846946c30","seed_id":"20c610421af1d8bd","seed_time":"1671191655615","platform":"5","device_fp":"38d7eeb3cb5e7","app_name":"account_cn","ext_fields":"{\"userAgent\":\"Mozilla/5.0 (Linux; Android 13; M2101K9C Build/TKQ1.220829.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/113.0.5672.76 Mobile Safari/537.36 miHoYoBBS/2.51.1\",\"browserScreenSize\":343089,\"maxTouchPoints\":5,\"isTouchSupported\":true,\"browserLanguage\":\"zh-CN\",\"browserPlat\":\"Linux aarch64\",\"browserTimeZone\":\"Asia/Shanghai\",\"webGlRender\":\"Adreno (TM) 642\",\"webGlVendor\":\"Qualcomm\",\"numOfPlugins\":0,\"listOfPlugins\":\"unknown\",\"screenRatio\":2.75,\"deviceMemory\":\"8\",\"hardwareConcurrency\":\"8\",\"cpuClass\":\"unknown\",\"ifNotTrack\":\"unknown\",\"ifAdBlock\":0,\"hasLiedResolution\":1,\"hasLiedOs\":0,\"hasLiedBrowser\":0}"}
> ```
> 
> 返回内容：
> 
> ```json
> {"retcode":0,"message":"OK","data":{"device_fp":"38d7eeb3cb5e7","code":200,"msg":"ok"}}
> ```

其实我也没搞太明白逻辑，我重装米游社后一段时间的header其实是不带这个的，估计是后面哪次验证加上？另外已经触发这个的账号后面再重新加上fp似乎也没法去掉验证码。不过我之前任填一个也是能用的（和不填相比），但是昨天又不能任填了，只能拿他下发的了

**Comment by Kamisato-Ayaka-233** [comment]
（emm，目前只发现每日便签相关的接口需要这个fp？）

**Comment by Kamisato-Ayaka-233** [comment]
好了，添加完毕。

**Comment by Kamisato-Ayaka-233** [comment]
https://github.com/Genshin-bots/gsuid_core/blob/2aff12e8d3b74160dbcb4f4407b7b1f22d82f718/gsuid_core/utils/api/mys/request.py#L131

可以康康这个项目的代码（似乎只要随便传入个合法的`device_fp`就可以了）

**Comment by Witnesscm** [comment]
https://github.com/UIGF-org/mihoyo-api-collect/issues/5#issuecomment-1594894282
