### ISSUE TITLE
现在4X salt和DS2算法有变化吗？生成的DS无法使用。

### ISSUE THREAD

**Issue by Crokily** [UIGF-org/mihoyo-api-collect#9]
按照鉴权那页写的js，
let salt = 'xV8v4Qu54lUKrEYFZkJhB8cuOh9Asafs';
let time = new Date().getTime().toString().substring(0, 10);
let random = Math.floor(Math.random() * 100001 + 100001);
let body = '';
let query = "role_id=xxxxx&server=prod_gf_cn&isPrev=&schedule_type=1&need_all=true"
let sign = md5("salt=" + salt + "&t=" + time + "&r=" + random + "&b=" + body + "&q=" + query);
console.log(time + "," + random + "," + sign)

header是
Host: api-takumi-record.mihoyo.com
DS:ds
x-rpc-app_version: 2.52.1
x-rpc-client_type: 5

用米游社抓包出来的ds放进去能用，用上述代码生成的ds丢header里会报-10001错误，代码应该没错吧，请问是不是算法或salt改变了？

**Comment by Kamisato-Ayaka-233** [comment]
一切没有变呀，你的`query`没有排序。

把`query`的代码改成这样：

```javascript
const query = "role_id=xxxxx&server=prod_gf_cn&isPrev=&schedule_type=1&need_all=true".split('&').sort().join('&')
```

**Comment by Crokily** [comment]
是了，问题解决，我看的不够仔细，感谢！
